language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
- 2.7
env:
  matrix:
  - CODECOV_TOKEN=bebb1336-846a-4e5a-a511-b3b6faa0f99b
  global:
  - secure: Q3pq5RPrKRzM6ZPutCA9rFMTN8znMndwRCHDQUEntTdWgZdRaip4zwVkzSInJAW0RgEjE8WB3vRgojyy1//7QVJjDyNEEZLNcxouMgBeNTqzje+9wOgPONijfG7ZRhhl84LQU+8zNsoQhuqXkKVOBIz8ATzWGVNic4OHfLjKJUxzxVRHBUuYmWKyGecqyo10zSFMIDmgoyj//vpVYC8wyc+LrrJb34FZW5Di55rWxhn22f/4uvRmVy2XfEGJ2WbyYZhLO95w5k5uJ8GKKyHR+SDo+EknQscu77vPG6RoHn4tIgkQ1KQaqh2hr60jWSEiQV97HBEJbAw68KMh5CgL/t2IiSF9TOf3/qJImq2Q+O6K8O15Emip9faW+BMOeXJmTh0ZugVTGhAzm7DqBjhWJ9+94cz3YzseOZUlyvTpfcX6z1mMIseHKWKqDKREj6NpC9gkF/aRHIoz1n2ceg+UWUUttrG1t5zxC7rzuktGHczfJYjTIwblOMaoc/wOo1j8FAp85fATBCSTc/UTyQ1PlMSteV6gk2XRblBq2nb2LxOEh5ynukb/hakXei0eyLm2DSitEWgDROBpATzKULJ+Wj1iAqymWZJ+aOEmmDBv0yHUcGP0szGoTElnfnKuvTq50WXB8zJmDxBZUNU0AwP7HIp6vO1mswvANK6l+cRzplE=
before_install:
- sudo apt-get update
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- source "$HOME/miniconda/etc/profile.d/conda.sh"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda install -y conda-build conda-verify anaconda-client
- conda config --set anaconda_upload no
install:
- pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: rymurr
  password:
    secure: RGt1Ga26z3caVH8dQd9NWWcJpxsXMlFcnMZEpbsBz+8GUh8khwvmUfDL2XslPeV1luMySGUlUIbEQAl6didn0cNtpXA/yxHHWyJYJ8ekqC2OY75zJtBP5ek34fxjlTGGMHKxngVCpIZb6k4izD4/x/DMAZg4W2iag16sSQhyUpdqVXFJ5EFncslY1QSXOd4mgY6auGCQxaxYPHYfHUbq8RONgeeoDdCUBl+xeGcpcKeK/GKIvN6wbH+/d5C8FchzwFjpoiLFBJdVCkcShyHbBa672bEcjPjvpjo6wd3+nGQLUE59kU1Fd2PD4qnXwYmj/YNYt+3Pkht/sDQEtQghKowNPJj379oCSr763LXr3JN4EpUFPMrTeuPltJUv8HrJxz3mm3r80EtHZjZkN4t8mxUyK/oZHXBfQ2vW/V6QwLwLrAJ7STqWmxjRO4pTO/+viSBWpxWkYIOOPudEFaMKSg35tkZRO/auWgVbsQym5Z+k4RIDWg5V6iPJ+eD/zCZZ3PpHsDDwDQo517AeF8qwONYT+U0tt04hj+Y7LCyi8UNAxSm2f0EQmwhAGlWeRGNWqpI+pBNePYw0d83VjR1JFVmSSMqbER5GgG9gLiJwelBtAnEIjH28SZwkl/EwjhGM2CEYyVJer13lUNmDhRc2dngSptx+SrXuaVy3ksR2Q34=
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
    repo: rymurr/dremio_client
