language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
- 2.7
env:
  matrix:
  - CODECOV_TOKEN=2e3c0144-c10f-4d20-851a-7d24252aa684
  global:
  - secure: Q3pq5RPrKRzM6ZPutCA9rFMTN8znMndwRCHDQUEntTdWgZdRaip4zwVkzSInJAW0RgEjE8WB3vRgojyy1//7QVJjDyNEEZLNcxouMgBeNTqzje+9wOgPONijfG7ZRhhl84LQU+8zNsoQhuqXkKVOBIz8ATzWGVNic4OHfLjKJUxzxVRHBUuYmWKyGecqyo10zSFMIDmgoyj//vpVYC8wyc+LrrJb34FZW5Di55rWxhn22f/4uvRmVy2XfEGJ2WbyYZhLO95w5k5uJ8GKKyHR+SDo+EknQscu77vPG6RoHn4tIgkQ1KQaqh2hr60jWSEiQV97HBEJbAw68KMh5CgL/t2IiSF9TOf3/qJImq2Q+O6K8O15Emip9faW+BMOeXJmTh0ZugVTGhAzm7DqBjhWJ9+94cz3YzseOZUlyvTpfcX6z1mMIseHKWKqDKREj6NpC9gkF/aRHIoz1n2ceg+UWUUttrG1t5zxC7rzuktGHczfJYjTIwblOMaoc/wOo1j8FAp85fATBCSTc/UTyQ1PlMSteV6gk2XRblBq2nb2LxOEh5ynukb/hakXei0eyLm2DSitEWgDROBpATzKULJ+Wj1iAqymWZJ+aOEmmDBv0yHUcGP0szGoTElnfnKuvTq50WXB8zJmDxBZUNU0AwP7HIp6vO1mswvANK6l+cRzplE=
before_install:
- sudo apt-get update
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- source "$HOME/miniconda/etc/profile.d/conda.sh"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda install -y conda-build conda-verify anaconda-client
- conda config --set anaconda_upload no
install:
- pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: ZlrTMmPU34BFi4atUeBDiOUmZDE5KC2jBcAunX/ocoDeK98hXw9V8ywVWX92cWLgRR3muHFKE5GSeo6+kBqDEN2wS1wROIZu/TsjPIwqS2Ysqa9P+PCyMK5LZ7DAIPNaOV7NcUaagjMF9vSYUqMdnLex28NykR3fNyMz2eleBTJxTFxjVUPnK+mwLWQ/OzWWowWBbZm5b8tz5uB0MGNPB36b9YRjEsBqT3Pn4jo+cQx1BKH7FiTMqNX29tFVSWJBn9b73ioCM9ceAswlt6IJVXFVqbWr5OdsVf3OTMuadVJJTqumKpLIVd+OQu7pfBmiK3ywbAsEngFC5Fdx5yNURM9SHqY/lnjMJ5rCYjgPaq5/IoUoGP/RJz5ZQmL6uP6SBadfYaeZ0Ihc8FxzsfUxzLLd7Ywo39Kh09iVTtHS3w6M28cKb0lvGxRndqcmfOylelZVjl6OoUaiU8at/6jNPBApzrACTsUbwRJ/HAeJQbTl5N2j4hVfzzFpmxvVsLGWgGIauJYapX1Mz9gl383lF/JsVBtXthcxCkNT2DmHjBxJLS5jhLVev7PRAZPp6fpuMOe0OojMyGo2Mlttn3E6/POhCTKGpv5ZXGTXNMw44lkX66TT4cla+hBOJxaxLFCvAXCPy48rS3zdXH3FG+bqhas16rwxbgc6pVLnrWyxivo=
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
    repo: rymurr/dremio_client
